import { cache } from "react";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { fetchPublicReportBySlug } from "../../../lib/reports";

/**
 * Public, shareable report page (design D16). Anyone holding the unguessable /r/<slug> URL can
 * view the report — there is no auth. The row is resolved by public_slug through the service-role
 * client inside lib/reports (a narrow, slug-scoped RLS bypass; a NULL-slug row is never
 * reachable, and only title + html are read). A slug that matches nothing, or a row with no
 * rendered html, 404s.
 *
 * force-dynamic: slugs are minted at runtime, so there is nothing to prerender. noindex: reports
 * are per-user data behind an unguessable link, never our own indexable content.
 */
export const dynamic = "force-dynamic";

/** Memoize per request so generateMetadata and the page body share ONE DB read. */
const loadReport = cache(fetchPublicReportBySlug);

const NOINDEX = { index: false, follow: false } as const;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const report = await loadReport(slug);
  if (!report) {
    return { title: "Report not found", robots: NOINDEX };
  }
  return {
    title: report.title ?? "SEO Report",
    description: "A shareable SEO report generated by SeoGrep.",
    robots: NOINDEX,
  };
}

export default async function PublicReportPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const report = await loadReport(slug);
  if (!report) {
    notFound();
  }

  // dangerouslySetInnerHTML is SAFE here and deliberate: report.html is produced entirely
  // server-side by our OWN renderReportHtml (apps/mcp report/html.ts) from structured data, with
  // every dynamic value (title, domain, crawled URLs, GSC queries) HTML-escaped at render time —
  // it is never raw user-authored markup. The stored document is self-contained (inline CSS, no
  // external requests), so we inject it verbatim and the browser renders its styles + body; the
  // canonical <head> metadata is supplied by generateMetadata above.
  return <div dangerouslySetInnerHTML={{ __html: report.html }} />;
}
